// Datenquelle – erweitere hier die Liste
// Kategorien
const TOP_CATEGORIES = ["Keep for Quests","Keep for Projects","Safe to Recycle","Workshop Upgrades"];
const WORKSHOP_SUBS = ["Scrappy","Gunsmith","Medical Lab","Explosive Station","Gear Bench","Refiner","Utility Station"];

const CAT_COLORS = {
  "Keep for Quests": "bg-amber-500/15 text-amber-300 ring-1 ring-amber-500/30",
  "Keep for Projects": "bg-sky-500/15 text-sky-300 ring-1 ring-sky-500/30",
  "Safe to Recycle": "bg-emerald-500/15 text-emerald-300 ring-1 ring-emerald-500/30",
  "Workshop Upgrades": "bg-violet-500/15 text-violet-300 ring-1 ring-violet-500/30",
};

const SUB_COLORS = {
  "Scrappy": "bg-stone-500/20 text-stone-200",
  "Gunsmith": "bg-zinc-500/20 text-zinc-200",
  "Medical Lab": "bg-rose-500/20 text-rose-200",
  "Explosive Station": "bg-orange-500/20 text-orange-200",
  "Gear Bench": "bg-cyan-500/20 text-cyan-200",
  "Refiner": "bg-lime-500/20 text-lime-200",
  "Utility Station": "bg-fuchsia-500/20 text-fuchsia-200",
};

// Starter-Daten
const ITEMS = [
  // Keep for Quests
  { name: "Leaper Pulse Unit", category: "Keep for Quests", notes: "Quest turn-in" },
  { name: "Power Rod", category: "Keep for Quests" },
  { name: "Rocketeer Driver", category: "Keep for Quests" },
  { name: "Surveyor Vault", category: "Keep for Quests" },
  { name: "Antiseptic", category: "Keep for Quests" },
  { name: "Hornet Driver", category: "Keep for Quests" },
  { name: "Syringe", category: "Keep for Quests" },
  { name: "Wasp Driver", category: "Keep for Quests" },
  { name: "Water Pump", category: "Keep for Quests" },
  { name: "Snitch Scanner", category: "Keep for Quests" },

  // Keep for Projects
  { name: "Leaper Pulse Unit", category: "Keep for Projects" },
  { name: "Magnetic Accelerator", category: "Keep for Projects" },
  { name: "Exodus Modules", category: "Keep for Projects" },
  { name: "Adv. Electrical Components", category: "Keep for Projects" },
  { name: "Humidifier", category: "Keep for Projects" },
  { name: "Sensors", category: "Keep for Projects" },
  { name: "Cooling Fan", category: "Keep for Projects" },
  { name: "Battery", category: "Keep for Projects" },
  { name: "Light Bulb", category: "Keep for Projects" },
  { name: "Electrical Components", category: "Keep for Projects" },
  { name: "Wires", category: "Keep for Projects" },
  { name: "Durable Cloth", category: "Keep for Projects" },
  { name: "Steel Spring", category: "Keep for Projects" },
  { name: "ARC Alloy", category: "Keep for Projects" },
  { name: "Rubber Parts", category: "Keep for Projects" },
  { name: "Metal Parts", category: "Keep for Projects" },

  // Safe to Recycle (sample)
  { name: "Accordion", category: "Safe to Recycle" },
  { name: "Alarm Clock", category: "Safe to Recycle" },
  { name: "ARC Coolant", category: "Safe to Recycle" },
  { name: "ARC Flex Rubber", category: "Safe to Recycle" },
  { name: "ARC Performance Steel", category: "Safe to Recycle" },
  { name: "ARC Synthetic Resin", category: "Safe to Recycle" },
  { name: "ARC Thermo Lining", category: "Safe to Recycle" },
  { name: "Bicycle Pump", category: "Safe to Recycle" },
  { name: "Broken Flashlight", category: "Safe to Recycle" },
  { name: "Broken Guidance System", category: "Safe to Recycle" },
  { name: "Broken Handcuffs", category: "Safe to Recycle" },
  { name: "Broken Handheld Radio", category: "Safe to Recycle" },
  { name: "Broken Taser", category: "Safe to Recycle" },
  { name: "Burned ARC Circuitry", category: "Safe to Recycle" },
  { name: "Camera Lens", category: "Safe to Recycle" },
  { name: "Candle Holder", category: "Safe to Recycle" },
  { name: "Coolant", category: "Safe to Recycle" },
  { name: "Cooling Coil", category: "Safe to Recycle" },
  { name: "Crumpled Plastic Bootle", category: "Safe to Recycle" },
  { name: "Damaged ARC Motion Core", category: "Safe to Recycle" },
  { name: "Damaged ARC Powercell", category: "Safe to Recycle" },
  { name: "Deflated Football", category: "Safe to Recycle" },
  { name: "Diving Googles", category: "Safe to Recycle" },
  { name: "Dried-Out ARC Resin", category: "Safe to Recycle" },
  { name: "Expired Respirator", category: "Safe to Recycle" },
  { name: "Flute", category: "Safe to Recycle" },
  { name: "Frying Pan", category: "Safe to Recycle" },
  { name: "Garlic Press", category: "Safe to Recycle" },
  { name: "Headphones", category: "Safe to Recycle" },
  { name: "Ice Cream Scooper", category: "Safe to Recycle" },
  { name: "Household Cleaner", category: "Safe to Recycle" },
  { name: "Impure ARC Coolant", category: "Safe to Recycle" },
  { name: "Industrial Charger", category: "Safe to Recycle" },
  { name: "Industrial Magnet", category: "Safe to Recycle" },
  { name: "Metal Brackets", category: "Safe to Recycle" },
  { name: "Number Plate", category: "Safe to Recycle" },
  { name: "Polluted Air Filter", category: "Safe to Recycle" },
  { name: "Portable TV", category: "Safe to Recycle" },
  { name: "Power Bank", category: "Safe to Recycle" },
  { name: "Projector", category: "Safe to Recycle" },
  { name: "Radio", category: "Safe to Recycle" },
  { name: "Remote Control", category: "Safe to Recycle" },
  { name: "Ripped Safety Vest", category: "Safe to Recycle" },
  { name: "Rollbot Part", category: "Safe to Recycle" },
  { name: "Rubber Pad", category: "Safe to Recycle" },
  { name: "Ruined Accordion", category: "Safe to Recycle" },
  { name: "Ruined Baton", category: "Safe to Recycle" },
  { name: "Ruined Handcuffs", category: "Safe to Recycle" },
  { name: "Ruined Parachute", category: "Safe to Recycle" },
  { name: "Ruined Riot Shield", category: "Safe to Recycle" },
  { name: "Ruined Tactical Vest", category: "Safe to Recycle" },
  { name: "Rusted Bolts", category: "Safe to Recycle" },
  { name: "Rusty ARC Steel", category: "Safe to Recycle" },
  { name: "Spotter Relay", category: "Safe to Recycle" },
  { name: "Spring Cushion", category: "Safe to Recycle" },
  { name: "Tattered ARC Lining", category: "Safe to Recycle" },
  { name: "Tattered Clothes", category: "Safe to Recycle" },
  { name: "Thermostat", category: "Safe to Recycle" },
  { name: "Torn Blanket", category: "Safe to Recycle" },
  { name: "Turbo Pump", category: "Safe to Recycle" },
  { name: "Water Filter", category: "Safe to Recycle" },

  // Workshop – Scrappy
  { name: "Dog Collar", category: "Workshop Upgrades", subCategory: "Scrappy", notes: "Level 2" },
  { name: "Lemon", category: "Workshop Upgrades", subCategory: "Scrappy", notes: "Level 3" },
  { name: "Apricot", category: "Workshop Upgrades", subCategory: "Scrappy", notes: "Level 3" },
  { name: "Prickly Pear", category: "Workshop Upgrades", subCategory: "Scrappy", notes: "Level 4" },
  { name: "Olives", category: "Workshop Upgrades", subCategory: "Scrappy", notes: "Level 4" },
  { name: "Cat Bed", category: "Workshop Upgrades", subCategory: "Scrappy", notes: "Level 4" },
  { name: "Mushroom", category: "Workshop Upgrades", subCategory: "Scrappy", notes: "Level 5" },
  { name: "Apricot", category: "Workshop Upgrades", subCategory: "Scrappy", notes: "Level 5" },
  { name: "Very Comfortable Pillow", category: "Workshop Upgrades", subCategory: "Scrappy", notes: "Level 5" },

  // Gunsmith
  { name: "Rusted Tools", category: "Workshop Upgrades", subCategory: "Gunsmith", notes: "Level 2" },
  { name: "Mechanical Components", category: "Workshop Upgrades", subCategory: "Gunsmith", notes: "Level 2" },
  { name: "Wasp Driver", category: "Workshop Upgrades", subCategory: "Gunsmith", notes: "Level 2" },
  { name: "Rusted Gear", category: "Workshop Upgrades", subCategory: "Gunsmith", notes: "Level 3" },
  { name: "Adv. Mechanical Components", category: "Workshop Upgrades", subCategory: "Gunsmith", notes: "Level 3" },
  { name: "Sentinel Firing Core", category: "Workshop Upgrades", subCategory: "Gunsmith", notes: "Level 3" },

  // Medical Lab
  { name: "Cracked Bioscanner", category: "Workshop Upgrades", subCategory: "Medical Lab", notes: "Level 2" },
  { name: "Durable Cloth", category: "Workshop Upgrades", subCategory: "Medical Lab", notes: "Level 2" },
  { name: "Tick Pod", category: "Workshop Upgrades", subCategory: "Medical Lab", notes: "Level 2" },
  { name: "Rusted Shut Medical Kit", category: "Workshop Upgrades", subCategory: "Medical Lab", notes: "Level 3" },
  { name: "Antiseptic", category: "Workshop Upgrades", subCategory: "Medical Lab", notes: "Level 3" },
  { name: "Surveyor Vault", category: "Workshop Upgrades", subCategory: "Medical Lab", notes: "Level 3" },

  // Explosive Station
  { name: "Synthesized Fuel", category: "Workshop Upgrades", subCategory: "Explosive Station", notes: "Level 2"  },
  { name: "Crude Explosives", category: "Workshop Upgrades", subCategory: "Explosive Station", notes: "Level 2"  },
  { name: "Pop Trigger", category: "Workshop Upgrades", subCategory: "Explosive Station", notes: "Level 2"  },
  { name: "Laboratory Reagents", category: "Workshop Upgrades", subCategory: "Explosive Station", notes: "Level 3"  },
  { name: "Explosive Compound", category: "Workshop Upgrades", subCategory: "Explosive Station", notes: "Level 3"  },
  { name: "Rocketeer Driver", category: "Workshop Upgrades", subCategory: "Explosive Station", notes: "Level 3"  },

  // Gear Bench
  { name: "Power Cable", category: "Workshop Upgrades", subCategory: "Gear Bench", notes: "Level 2" },
  { name: "Hornet Driver", category: "Workshop Upgrades", subCategory: "Gear Bench", notes: "Level 2" },
  { name: "Electrical Components", category: "Workshop Upgrades", subCategory: "Gear Bench", notes: "Level 2" },
  { name: "Industrial Battery", category: "Workshop Upgrades", subCategory: "Gear Bench", notes: "Level 3" },
  { name: "Adv. Electrical Components", category: "Workshop Upgrades", subCategory: "Gear Bench", notes: "Level 3" },
  { name: "Bastion Cell", category: "Workshop Upgrades", subCategory: "Gear Bench", notes: "Level 3" },

  // Refiner
  { name: "Toaster", category: "Workshop Upgrades", subCategory: "Refiner", notes: "Level 2" },
  { name: "ARC Motion Core", category: "Workshop Upgrades", subCategory: "Refiner", notes: "Level 2" },
  { name: "Fireball Burner", category: "Workshop Upgrades", subCategory: "Refiner", notes: "Level 2" },
  { name: "Motor", category: "Workshop Upgrades", subCategory: "Refiner", notes: "Level 3" },
  { name: "ARC Circuitry", category: "Workshop Upgrades", subCategory: "Refiner", notes: "Level 3" },
  { name: "Bombardier Cell", category: "Workshop Upgrades", subCategory: "Refiner", notes: "Level 3" },

  // Utility Station
  { name: "Damaged Heat Sink", category: "Workshop Upgrades", subCategory: "Utility Station", notes: "Level 2" },
  { name: "Electrical Components", category: "Workshop Upgrades", subCategory: "Utility Station", notes: "Level 2" },
  { name: "Snitch Scanner", category: "Workshop Upgrades", subCategory: "Utility Station", notes: "Level 2" },
  { name: "Fried Motherboard", category: "Workshop Upgrades", subCategory: "Utility Station", notes: "Level 3" },
  { name: "Adv. Electrical Components", category: "Workshop Upgrades", subCategory: "Utility Station", notes: "Level 3" },
  { name: "Leaper Pulse Unit", category: "Workshop Upgrades", subCategory: "Utility Station", notes: "Level 3" },
];
